// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvWwg3ADJPLLHakaAF4KrnchATRQk140',
    appId: '1:952462688777:web:6dc6ff03da3c4c335b2ed8',
    messagingSenderId: '952462688777',
    projectId: 'evaluacionpractica-8bb3f',
    authDomain: 'evaluacionpractica-8bb3f.firebaseapp.com',
    storageBucket: 'evaluacionpractica-8bb3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqNoBpFM9fxJnWnMHuBgvFYWXghpiRDs',
    appId: '1:836333937912:android:644de08b77960a4e56070d',
    messagingSenderId: '836333937912',
    projectId: 'appointment-app-59053',
    storageBucket: 'appointment-app-59053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kpyZFsjPOkwOSYUjJ4o5fOGBr__qh98',
    appId: '1:952462688777:ios:03bb5154b0680b445b2ed8',
    messagingSenderId: '952462688777',
    projectId: 'evaluacionpractica-8bb3f',
    storageBucket: 'evaluacionpractica-8bb3f.firebasestorage.app',
    iosBundleId: 'com.example.evaluacionPractica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_kpyZFsjPOkwOSYUjJ4o5fOGBr__qh98',
    appId: '1:952462688777:ios:03bb5154b0680b445b2ed8',
    messagingSenderId: '952462688777',
    projectId: 'evaluacionpractica-8bb3f',
    storageBucket: 'evaluacionpractica-8bb3f.firebasestorage.app',
    iosBundleId: 'com.example.evaluacionPractica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcvWwg3ADJPLLHakaAF4KrnchATRQk140',
    appId: '1:952462688777:web:1c5faf4a443fd87d5b2ed8',
    messagingSenderId: '952462688777',
    projectId: 'evaluacionpractica-8bb3f',
    authDomain: 'evaluacionpractica-8bb3f.firebaseapp.com',
    storageBucket: 'evaluacionpractica-8bb3f.firebasestorage.app',
  );
}